apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-sync-phase-1
spec:
  destination:
    namespace: app-sync-phase-1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: v07-argocd-sync-phases-waves/sync-phases-waves-manifests-examples
    repoURL: https://github.com/rezacloner1372/argocd-tutorial.git
    targetRevision: main
  syncPolicy:
    automated: {}
