apiVersion: batch/v1
kind: Job
metadata:
  name: mattermost-post-job-failure
  annotations:
    argocd.argoproj.io/hook: SyncFail
spec:
  template:
    spec:
      containers:
        - name: mattermost-failure
          image: mattermost:final
          command: [ "python3", "mattermost_api.py"]
          env:
          - name: message
            value: "MESSAGE FROM ARGOCD: The last sync is:  *** Sync Failed ***"
          - name: url
            value: "kind-mattermost.com"
          - name: token
            value: "ntxgwr6hf386jj3ihc4tjf7ego"
          - name: scheme
            value: "http"
          - name: port
            value: "80 "
          - name: channel_name
            value: "Argocd"
          - name: team_name
            value: "Argocd"
      restartPolicy: Never
  backoffLimit: 0
